/*
 */
package tareapractica4;

import javax.swing.JOptionPane;

/**
 *
 * @author ZoeyTato [Zoila Garcia 2021-1514]
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        plOperaciones = new javax.swing.JPanel();
        btnSqrt = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnExponenciacion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        plTitulo1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        plOperaciones1 = new javax.swing.JPanel();
        btnConvertir = new javax.swing.JButton();
        btnLimpiar2 = new javax.swing.JButton();
        plValores2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCelsius = new javax.swing.JTextField();
        txtFarenheit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(88, 41, 137));

        lblTitulo.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tareapractica4/calculadoracolor.png"))); // NOI18N
        lblTitulo.setText("Convertidor de Zoila");

        javax.swing.GroupLayout plTituloLayout = new javax.swing.GroupLayout(plTitulo);
        plTitulo.setLayout(plTituloLayout);
        plTituloLayout.setHorizontalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        plTituloLayout.setVerticalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 470, -1));

        plValores.setBackground(new java.awt.Color(204, 204, 255));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Valor a:");
        plValores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtValor1.setBackground(new java.awt.Color(255, 255, 255));
        txtValor1.setForeground(new java.awt.Color(51, 51, 51));
        txtValor1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtValor1.addActionListener(this::txtValor1ActionPerformed);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, 40));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Resultado");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtRespuesta.setBackground(new java.awt.Color(153, 153, 255));
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRespuesta.setForeground(new java.awt.Color(51, 51, 51));
        txtRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRespuesta.addActionListener(this::txtRespuestaActionPerformed);
        plValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 70));

        txtValor2.setBackground(new java.awt.Color(255, 255, 255));
        txtValor2.setForeground(new java.awt.Color(51, 51, 51));
        txtValor2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtValor2.addActionListener(this::txtValor2ActionPerformed);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, 40));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Valor b:");
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, 360));

        plOperaciones.setBackground(new java.awt.Color(184, 171, 198));
        plOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSqrt.setText("sqrt(a)");
        btnSqrt.addActionListener(this::btnSqrtActionPerformed);
        plOperaciones.add(btnSqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, -1));

        btnSuma.setText("Sumar");
        btnSuma.addActionListener(this::btnSumaActionPerformed);
        plOperaciones.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, -1));

        btnResta.setText("Restar");
        btnResta.addActionListener(this::btnRestaActionPerformed);
        plOperaciones.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        btnMultiplicacion.setText("Multiplicar");
        btnMultiplicacion.addActionListener(this::btnMultiplicacionActionPerformed);
        plOperaciones.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        btnDivision.setText("Dividir");
        btnDivision.addActionListener(this::btnDivisionActionPerformed);
        plOperaciones.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        btnExponenciacion.setText("a^b");
        btnExponenciacion.addActionListener(this::btnExponenciacionActionPerformed);
        plOperaciones.add(btnExponenciacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        plOperaciones.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, -1));

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 170, 360));

        plTitulo1.setBackground(new java.awt.Color(88, 41, 137));

        lblTitulo1.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tareapractica4/calculadoracolor.png"))); // NOI18N
        lblTitulo1.setText("Calculadora de Zoila");

        javax.swing.GroupLayout plTitulo1Layout = new javax.swing.GroupLayout(plTitulo1);
        plTitulo1.setLayout(plTitulo1Layout);
        plTitulo1Layout.setHorizontalGroup(
            plTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTitulo1Layout.createSequentialGroup()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        plTitulo1Layout.setVerticalGroup(
            plTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTitulo1Layout.createSequentialGroup()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(plTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        plOperaciones1.setBackground(new java.awt.Color(184, 171, 198));
        plOperaciones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConvertir.setBackground(new java.awt.Color(204, 204, 255));
        btnConvertir.setForeground(new java.awt.Color(51, 51, 51));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(this::btnConvertirActionPerformed);
        plOperaciones1.add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        btnLimpiar2.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar2.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpiar2.setText("Limpiar campos");
        btnLimpiar2.addActionListener(this::btnLimpiar2ActionPerformed);
        plOperaciones1.add(btnLimpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        getContentPane().add(plOperaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 170, 210));

        plValores2.setBackground(new java.awt.Color(204, 204, 255));
        plValores2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Celsius:");
        plValores2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtCelsius.setBackground(new java.awt.Color(255, 255, 255));
        txtCelsius.setForeground(new java.awt.Color(51, 51, 51));
        txtCelsius.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCelsius.addActionListener(this::txtCelsiusActionPerformed);
        txtCelsius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelsiusKeyTyped(evt);
            }
        });
        plValores2.add(txtCelsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 40));

        txtFarenheit.setBackground(new java.awt.Color(255, 255, 255));
        txtFarenheit.setForeground(new java.awt.Color(51, 51, 51));
        txtFarenheit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFarenheit.addActionListener(this::txtFarenheitActionPerformed);
        txtFarenheit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFarenheitKeyTyped(evt);
            }
        });
        plValores2.add(txtFarenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 40));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Farenheit:");
        plValores2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        getContentPane().add(plValores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 300, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        validarCampo();
        calcularRaiz();
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2ActionPerformed

        limpiarConvertidor();
    }//GEN-LAST:event_btnLimpiar2ActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        validarCampos();
        dividirValores();
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnExponenciacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponenciacionActionPerformed
        validarCampos();
        exponenciarValores();

    }//GEN-LAST:event_btnExponenciacionActionPerformed

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Debe ingresar números.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor2ActionPerformed

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Debe ingresar números.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelsiusActionPerformed

    private void txtCelsiusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelsiusKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Debe ingresar números.");
            evt.consume();
        }
    }//GEN-LAST:event_txtCelsiusKeyTyped

    private void txtFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFarenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFarenheitActionPerformed

    private void txtFarenheitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFarenheitKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Debe ingresar números.");
            evt.consume();
        }
    }//GEN-LAST:event_txtFarenheitKeyTyped

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        if ((txtCelsius.getText().trim().length() <= 0) && (txtFarenheit.getText().trim().length() <= 0)) {
            JOptionPane.showMessageDialog(null, "Debe llenar 1 de los campos.");
        } else if ((txtCelsius.getText().trim().length() > 0) && (txtFarenheit.getText().trim().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Solo puede llenar 1 de los campos.");
        } else {
            if ((txtCelsius.getText().trim().length() > 0)) {
                Calculadora conv = new Calculadora();
                double respuesta = conv.convertirFarenheit(Double.parseDouble(txtCelsius.getText()));
                txtFarenheit.setText(respuesta + "");
            }
            else if ((txtFarenheit.getText().trim().length() > 0)) {
                Calculadora conv = new Calculadora();
                double respuesta = conv.convertirCelsius(Double.parseDouble(txtFarenheit.getText()));
                txtCelsius.setText(respuesta + "");
            }
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void limpiarCampos() {
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
    }

    private void limpiarConvertidor() {
        txtCelsius.setText("");
        txtFarenheit.setText("");
        txtFarenheit.requestFocus();
    }

    private void validarCampo() {
        if (txtValor1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "No puede dejar Valor 1 vacío.");
        }
    }

    private void validarCampos() {
        if (txtValor1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "No puede dejar Valor 1 vacío.");
        } else if (txtValor2.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "No puede dejar Valor 2 vacío.");
        }
    }

    private void validarConvertidor() {
        if ((txtCelsius.getText().trim().length() <= 0) && (txtFarenheit.getText().trim().length() <= 0)) {
            JOptionPane.showMessageDialog(null, "Debe llenar 1 de los campos.");
        } else if ((txtCelsius.getText().trim().length() > 0) && (txtFarenheit.getText().trim().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Solo puede llenar 1 de los campos.");
        }
    }

    private void convertirTemperatura() {

    }

    private void sumarValores() {
        Calculadora calc = new Calculadora();
        double respuesta = calc.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");
    }

    private void restarValores() {
        Calculadora calc = new Calculadora();
        double respuesta = calc.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");
    }

    private void multiplicarValores() {
        Calculadora calc = new Calculadora();
        double respuesta = calc.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");
    }

    private void dividirValores() {
        Calculadora calc = new Calculadora();
        double respuesta = calc.dividir(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        if (respuesta == 0) {
            JOptionPane.showMessageDialog(null, "No puede dejar dividir con 0.");
        }
        txtRespuesta.setText(respuesta + "");
    }

    private void exponenciarValores() {
        Calculadora calc = new Calculadora();
        double respuesta = calc.exponenciar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");
    }

    private void calcularRaiz() {
        Calculadora calc = new Calculadora();
        double respuesta = calc.raizCuadrada(Double.parseDouble(txtValor1.getText()));
        txtRespuesta.setText(respuesta + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnExponenciacion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar2;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plOperaciones1;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plTitulo1;
    private javax.swing.JPanel plValores;
    private javax.swing.JPanel plValores2;
    private javax.swing.JTextField txtCelsius;
    private javax.swing.JTextField txtFarenheit;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
