package calculadora.guiCalculadora;

import convertidorgrados.ConvertidorGradosGui;
import javax.swing.JOptionPane;
import raizcuadrada_exponente.Raizcuadrada_Exponente;

public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        plOperaciones = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        btnModoConversor = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnRaizcuadrada = new javax.swing.JButton();
        btnExponenciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Basica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(102, 102, 102));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Básica");
        plTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/guiCalculadora/imagenes/calculadora.png"))); // NOI18N
        plTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, 46));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 80));

        plValores.setBackground(new java.awt.Color(153, 153, 153));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Respuesta:");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        txtRespuesta.setEditable(false);
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 50));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor 1:");
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtValor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, 30));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor 2:");
        plValores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtValor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor2ActionPerformed(evt);
            }
        });
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, 30));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 260));

        plOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        plOperaciones.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        btnModoConversor.setText("Modo Conversor");
        btnModoConversor.setMaximumSize(new java.awt.Dimension(90, 24));
        btnModoConversor.setMinimumSize(new java.awt.Dimension(90, 24));
        btnModoConversor.setPreferredSize(new java.awt.Dimension(90, 24));
        btnModoConversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoConversorActionPerformed(evt);
            }
        });
        plOperaciones.add(btnModoConversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, 30));
        btnModoConversor.getAccessibleContext().setAccessibleDescription("");

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.setMaximumSize(new java.awt.Dimension(47, 24));
        btnMultiplicar.setMinimumSize(new java.awt.Dimension(47, 24));
        btnMultiplicar.setPreferredSize(new java.awt.Dimension(47, 24));
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        plOperaciones.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        btnDividir.setText("Dividir");
        btnDividir.setMaximumSize(new java.awt.Dimension(90, 24));
        btnDividir.setMinimumSize(new java.awt.Dimension(90, 24));
        btnDividir.setPreferredSize(new java.awt.Dimension(90, 24));
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        plOperaciones.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        plOperaciones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 40));

        btnResetear.setText("Resetear");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });
        plOperaciones.add(btnResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 40));

        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        plOperaciones.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        btnRaizcuadrada.setText("Raizcuadrada");
        btnRaizcuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizcuadradaActionPerformed(evt);
            }
        });
        plOperaciones.add(btnRaizcuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 110, 30));

        btnExponenciar.setText("Exponenciar");
        btnExponenciar.setMaximumSize(new java.awt.Dimension(90, 24));
        btnExponenciar.setMinimumSize(new java.awt.Dimension(90, 24));
        btnExponenciar.setPreferredSize(new java.awt.Dimension(90, 24));
        btnExponenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExponenciarActionPerformed(evt);
            }
        });
        plOperaciones.add(btnExponenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 30));

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 260, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evalua que los valores ingresado del primer valor sean solo numeros
     * @param evt valor ingresado
     */
    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed

    }//GEN-LAST:event_txtValor2ActionPerformed

    /**
     * Evalua que los valores ingresado del segundo valor sean solo numeros
     * @param evt valor ingresado
     */
    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    /**
     * Boton que se encarga de llamar dos métodos para sumar los valores y valida que los campos sean correctos
     * @param evt Dar click
     */
    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_btnSumarActionPerformed

    /**
     * Botonque cierra la calculadora
     * @param evt Dar clik
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Boton que se encarga de llamar dos métodos para validar que los campos sean correctos y multiplicar los valores
     * @param evt Dar click
     */
    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    /**
     * Boton que se encarga de llamar un método para limpiar los campos
     * @param evt Dar click
     */
    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnResetearActionPerformed

    /**
     * Boton que redirige a la calculadora de conversión de grados
     * @param evt Dar click
     */
    private void btnModoConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoConversorActionPerformed
        ConvertidorGradosGui ventana = new ConvertidorGradosGui();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModoConversorActionPerformed

    /**
     * Boton que se encarga de llamar dos métodos para valida que los campos sean correctos y dividir los valores
     * @param evt Dar click
     */
    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        validarCampos();
        dividirValores();
    }//GEN-LAST:event_btnDividirActionPerformed

    /**
     * Boton que se encarga de llamar dos métodos para validar que los campos sean correctos y restar los valores
     * @param evt Dar click
     */
    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_btnRestarActionPerformed

    /**
     * Boton que se encarga de llamar un método para validar que el campo sea correcto y encontrar la raíz cuadradra del valor
     * @param evt Dar click
     */
    private void btnRaizcuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizcuadradaActionPerformed
        if(txtValor1.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, porque el campo esta vacio.");
            txtValor1.requestFocus();
        } else if(txtValor2.getText().trim().length() > 0){
            JOptionPane.showMessageDialog(null, "Favor dejar el valor 2 despejado, porque el campo necesario solamente es el primero para esta operación.");
            txtValor2.requestFocus();
            return;
        }
        raizCuadradaValores();
    }//GEN-LAST:event_btnRaizcuadradaActionPerformed

    private void btnExponenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponenciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExponenciarActionPerformed

    /**
     * Asegura que los campos no estén vacíos
     */
    private void validarCampos(){
        if(txtValor1.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, porque el campo esta vacio.");
            txtValor1.requestFocus();
        } else if(txtValor2.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 2, porque el campo esta vacio.");
            txtValor2.requestFocus();
        }
    }
    
    /**
     * Gestiona la suma de los valores ingresados
     */
    private void sumarValores(){
        Calculadora cal = new Calculadora();
        Double respuesta = cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    /**
     * Gestiona la resta de los valores ingresados
     */
    private void restarValores(){
        Calculadora cal = new Calculadora();
        Double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    /**
     * Gestiona la multiplicación de los valores ingresados
     */
    private void multiplicarValores(){
        Calculadora cal = new Calculadora();
        Double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    /**
     * Gestiona la división de los valores ingresados
     */
    private void dividirValores(){
        Calculadora cal = new Calculadora();
        if(Double.parseDouble(txtValor2.getText()) == 0){
            JOptionPane.showMessageDialog(null, "No es posible dividir un número por cero");
            txtValor2.requestFocus();
            return;
        }
        Double respuesta = cal.dividir(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    /**
     * Gestiona la raíz cuadrada del valor ingresado
     */
    private void raizCuadradaValores(){
        Raizcuadrada_Exponente cal = new Raizcuadrada_Exponente();
        
        Double respuesta = cal.raizcuadrada(Double.parseDouble(txtValor1.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    /**
     * Gestiona la potenciación del valore ingresado
     */
    private void exponenciarValores(){
        Raizcuadrada_Exponente cal = new Raizcuadrada_Exponente();
        Double respuesta = cal.exponenciar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    /**
     * Matiene los campos vacíos
     */
    private void limpiarCampos(){
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnExponenciar;
    private javax.swing.JButton btnModoConversor;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRaizcuadrada;
    private javax.swing.JButton btnResetear;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
