/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 * CalculadoraGUI
 *
 * Interfaz gráfica de una calculadora extendida.
 * Esta clase usa:
 * - javax.swing: para construir la interfaz gráfica (botones, paneles, textos).
 * - java.awt: para componentes como TextArea.
 * - javax.swing.JOptionPane: para mostrar mensajes de alerta al usuario.
 *
 * Permite:
 * - Operaciones básicas: suma, resta, multiplicación y división.
 * - Conversión de temperaturas: °C a °F y °F a °C.
 * - Operaciones matemáticas: raíz cuadrada y potencia.
 * - Registro de historial de operaciones en un área de texto.
 *
 * Maneja errores de entrada, como división entre cero y datos inválidos.
 *
 * Autor: Dalvi
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Constructor de la calculadora.
     *
     * Inicializa la interfaz gráfica y todos sus componentes.
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        txtValor1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        plOperaciones = new javax.swing.JPanel();
        btmSumar4 = new javax.swing.JButton();
        btmRestar = new javax.swing.JButton();
        btmMultiplicar = new javax.swing.JButton();
        btmDividir = new javax.swing.JButton();
        btmResetear = new javax.swing.JButton();
        btmCaF = new javax.swing.JButton();
        btmFaC = new javax.swing.JButton();
        btmRaiz = new javax.swing.JButton();
        btmPotencia = new javax.swing.JButton();
        btmBorrarHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(102, 102, 102));

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Extendida");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/Image1.png"))); // NOI18N

        javax.swing.GroupLayout plTituloLayout = new javax.swing.GroupLayout(plTitulo);
        plTitulo.setLayout(plTituloLayout);
        plTituloLayout.setHorizontalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTituloLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        plTituloLayout.setVerticalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        plValores.setBackground(new java.awt.Color(153, 153, 153));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Respuesta:");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 20));

        txtRespuesta.setEditable(false);
        txtRespuesta.setBackground(new java.awt.Color(255, 255, 255));
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRespuesta.setForeground(new java.awt.Color(51, 255, 0));
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRespuesta.addActionListener(this::txtRespuestaActionPerformed);
        plValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 190, 40));

        txtValor1.setBackground(new java.awt.Color(255, 255, 255));
        txtValor1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtValor1.setForeground(new java.awt.Color(0, 0, 0));
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addActionListener(this::txtValor1ActionPerformed);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 30));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor 1:");
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, -1, 20));

        txtValor2.setBackground(new java.awt.Color(255, 255, 255));
        txtValor2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtValor2.setForeground(new java.awt.Color(0, 0, 0));
        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addActionListener(this::txtValor2ActionPerformed);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, 30));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor 2:");
        plValores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 50));
        plValores.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 210));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 310, 380));

        plOperaciones.setBackground(new java.awt.Color(204, 204, 204));
        plOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmSumar4.setBackground(new java.awt.Color(255, 255, 255));
        btmSumar4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmSumar4.setForeground(new java.awt.Color(0, 0, 0));
        btmSumar4.setText("Sumar");
        btmSumar4.addActionListener(this::btmSumar4ActionPerformed);
        plOperaciones.add(btmSumar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 200, -1));

        btmRestar.setBackground(new java.awt.Color(255, 255, 255));
        btmRestar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmRestar.setForeground(new java.awt.Color(0, 0, 0));
        btmRestar.setText("Restar");
        btmRestar.addActionListener(this::btmRestarActionPerformed);
        plOperaciones.add(btmRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 200, -1));

        btmMultiplicar.setBackground(new java.awt.Color(255, 255, 255));
        btmMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        btmMultiplicar.setText("Multiplicar");
        btmMultiplicar.addActionListener(this::btmMultiplicarActionPerformed);
        plOperaciones.add(btmMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, -1));

        btmDividir.setBackground(new java.awt.Color(255, 255, 255));
        btmDividir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmDividir.setForeground(new java.awt.Color(0, 0, 0));
        btmDividir.setText("Dividir");
        btmDividir.addActionListener(this::btmDividirActionPerformed);
        plOperaciones.add(btmDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, -1));

        btmResetear.setBackground(new java.awt.Color(255, 255, 255));
        btmResetear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmResetear.setForeground(new java.awt.Color(0, 0, 0));
        btmResetear.setText("Resetear");
        btmResetear.addActionListener(this::btmResetearActionPerformed);
        plOperaciones.add(btmResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, 40));

        btmCaF.setBackground(new java.awt.Color(255, 255, 255));
        btmCaF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmCaF.setForeground(new java.awt.Color(0, 0, 0));
        btmCaF.setText("°C a °F");
        btmCaF.addActionListener(this::btmCaFActionPerformed);
        plOperaciones.add(btmCaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 200, -1));

        btmFaC.setBackground(new java.awt.Color(255, 255, 255));
        btmFaC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmFaC.setForeground(new java.awt.Color(0, 0, 0));
        btmFaC.setText("°F a °C");
        btmFaC.addActionListener(this::btmFaCActionPerformed);
        plOperaciones.add(btmFaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, -1));

        btmRaiz.setBackground(new java.awt.Color(255, 255, 255));
        btmRaiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmRaiz.setForeground(new java.awt.Color(0, 0, 0));
        btmRaiz.setText("Raíz");
        btmRaiz.addActionListener(this::btmRaizActionPerformed);
        plOperaciones.add(btmRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 200, -1));

        btmPotencia.setBackground(new java.awt.Color(255, 255, 255));
        btmPotencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmPotencia.setForeground(new java.awt.Color(0, 0, 0));
        btmPotencia.setText("Potencia");
        btmPotencia.addActionListener(this::btmPotenciaActionPerformed);
        plOperaciones.add(btmPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, -1));

        btmBorrarHistorial.setBackground(new java.awt.Color(255, 255, 255));
        btmBorrarHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmBorrarHistorial.setForeground(new java.awt.Color(0, 0, 0));
        btmBorrarHistorial.setText("Borrar Historial");
        btmBorrarHistorial.addActionListener(this::btmBorrarHistorialActionPerformed);
        plOperaciones.add(btmBorrarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 40));

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 310, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor2ActionPerformed

    /**
     * Valida que solo se ingresen números, coma o punto en el campo Valor 1.
     */
    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && numeros != ',' && numeros != '.') {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    /**
     * Evento del botón Restar.
     */
    private void btmRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRestarActionPerformed
        if (validarCampos()) {
            restarValores();
        }
    }//GEN-LAST:event_btmRestarActionPerformed

    /**
     * Resta 'Valor 2' de 'Valor 1' y muestra el resultado en 'Respuesta'.
     * También lo guarda en el historial. Maneja el caso en que el usuario
     * ingrese algo que no sea un número mostrando un mensaje de error.
     */
    private void restarValores() {
        try {
            Double valor1 = Double.parseDouble(txtValor1.getText().replace(",", "."));
            Double valor2 = Double.parseDouble(txtValor2.getText().replace(",", "."));

            Calculadora cal = new Calculadora();
            Double respuesta = cal.restar(valor1, valor2);

            txtRespuesta.setText(respuesta + "");

            textArea1.append(valor1 + " - " + valor2 + " = " + respuesta + "\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos");
        }
    }

    /**
     * Evento del botón Resetear. Limpia todos los campos.
     */
    private void btmResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmResetearActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btmResetearActionPerformed

    /**
     * Limpia los campos de entrada y resultado.
     */
    private void limpiarCampos() {
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
    }

    /**
     * Valida que solo se ingresen números, coma o punto en el campo Valor 2.
     */
    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && numeros != ',' && numeros != '.') {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    /**
     * Evento del botón Sumar.
     */
    private void btmSumar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSumar4ActionPerformed
        if (validarCampos()) {
            sumarValores();
        }
    }//GEN-LAST:event_btmSumar4ActionPerformed

    /**
     * Evento del botón Multiplicar.
     */
    private void btmMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMultiplicarActionPerformed
        if (validarCampos()) {
            multiplicarValores();
        }
    }//GEN-LAST:event_btmMultiplicarActionPerformed

    /**
     * Evento del botón Dividir.
     */
    private void btmDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDividirActionPerformed
        if (validarCampos()) {
            dividirValores();
        }
    }//GEN-LAST:event_btmDividirActionPerformed

    /**
     * Convierte el valor de 'Valor 1' de Celsius a Fahrenheit. Solo se permite
     * usar 'Valor 1'; si hay algo en 'Valor 2', avisa al usuario. Muestra el
     * resultado en 'Respuesta' y agrega la conversión al historial. Valida que
     * el número ingresado sea válido.
     */
    private void btmCaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCaFActionPerformed
        if (!txtValor2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Solo ingrese un valor en 'Valor 1' para la conversión");
            txtValor2.setText("");
            txtValor1.requestFocus();
            return;
        }

        try {
            double celsius = Double.parseDouble(txtValor1.getText().replace(",", "."));
            ConversorTemperatura conversor = new ConversorTemperatura();
            double fahrenheit = conversor.celsiusAFahrenheit(celsius);
            txtRespuesta.setText(fahrenheit + " °F");
            textArea1.append(celsius + " °C → " + fahrenheit + " °F\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido para la conversión");
        }
    }//GEN-LAST:event_btmCaFActionPerformed

    /**
     * Convierte el valor de 'Valor 1' de Fahrenheit a Celsius. Solo se permite
     * usar 'Valor 1'; si 'Valor 2' tiene algo, se limpia y avisa. El resultado
     * se muestra en 'Respuesta' y se guarda en el historial. Valida que el
     * usuario haya ingresado un número correcto.
     */
    private void btmFaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmFaCActionPerformed

        if (!txtValor2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Solo ingrese un valor en 'Valor 1' para la conversión");
            txtValor2.setText("");
            txtValor1.requestFocus();
            return;
        }

        try {
            double fahrenheit = Double.parseDouble(txtValor1.getText().replace(",", "."));
            ConversorTemperatura conversor = new ConversorTemperatura();
            double celsius = conversor.fahrenheitACelsius(fahrenheit);
            txtRespuesta.setText(celsius + " °C");
            textArea1.append(fahrenheit + " °F → " + celsius + " °C\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido para la conversión");
        }
    }//GEN-LAST:event_btmFaCActionPerformed

    /**
     * Calcula la raíz cuadrada del número ingresado en 'Valor 1'. No permite
     * números negativos, y en caso de error muestra un mensaje. El resultado se
     * muestra en 'Respuesta' y se agrega al historial.
     */
    private void btmRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRaizActionPerformed
        try {
            double valor = Double.parseDouble(txtValor1.getText().replace(",", "."));
            RaizExponente re = new RaizExponente();

            if (valor < 0) {
                JOptionPane.showMessageDialog(null, "No se puede calcular la raíz de un número negativo");
                txtValor1.requestFocus();
                return;
            }

            double resultado = re.raizCuadrada(valor);
            txtRespuesta.setText(String.valueOf(resultado));
            textArea1.append("√" + valor + " = " + resultado + "\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido");
        }
    }//GEN-LAST:event_btmRaizActionPerformed

    /**
     * Calcula el resultado de elevar 'Valor 1' a la potencia de 'Valor 2'.
     * Valida que ambos campos tengan números válidos. El resultado se muestra
     * en 'Respuesta' y se agrega al historial.
     */
    private void btmPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPotenciaActionPerformed

        if (txtValor1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor ingresar la base en 'Valor 1'");
            txtValor1.requestFocus();
            return;
        }

        if (txtValor2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor ingresar el exponente en 'Valor 2'");
            txtValor2.requestFocus();
            return;
        }

        try {
            double base = Double.parseDouble(txtValor1.getText().replace(",", "."));
            double exponente = Double.parseDouble(txtValor2.getText().replace(",", "."));

            RaizExponente re = new RaizExponente();
            double resultado = re.potencia(base, exponente);

            txtRespuesta.setText(String.valueOf(resultado));
            textArea1.append(base + " ^ " + exponente + " = " + resultado + "\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos en ambos campos");
        }
    }//GEN-LAST:event_btmPotenciaActionPerformed

    /**
     * Limpia todo el historial mostrado en el textArea1. No afecta los valores
     * ingresados ni el resultado actual.
     */
    private void btmBorrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBorrarHistorialActionPerformed
        textArea1.setText("");
    }//GEN-LAST:event_btmBorrarHistorialActionPerformed

    /**
     * Toma 'Valor 1' y 'Valor 2' y realiza la división: Valor 1 ÷ Valor 2.
     * Valida que el divisor no sea cero para evitar errores. Muestra el
     * resultado en 'Respuesta' y lo agrega al historial. Si se ingresa algo que
     * no sea un número, muestra un mensaje de error.
     */
    private void dividirValores() {
        try {
            Double valor1 = Double.parseDouble(txtValor1.getText().replace(",", "."));
            Double valor2 = Double.parseDouble(txtValor2.getText().replace(",", "."));

            if (valor2 == 0) {
                JOptionPane.showMessageDialog(null, "ERROR: No se puede dividir entre cero.");
                txtValor2.setText("");
                txtValor2.requestFocus();
            } else {
                Calculadora cal = new Calculadora();
                Double respuesta = cal.dividir(valor1, valor2);
                txtRespuesta.setText(respuesta + "");
                textArea1.append(valor1 + " ÷ " + valor2 + " = " + respuesta + "\n");
            }

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos");
        }

    }

    /**
     * Multiplica los valores ingresados en 'Valor 1' y 'Valor 2'. El resultado
     * se muestra en 'Respuesta' y se agrega al historial. Si se ingresa un
     * valor que no sea número, muestra un mensaje de error.
     */
    private void multiplicarValores() {
        try {
            Double valor1 = Double.parseDouble(txtValor1.getText().replace(",", "."));
            Double valor2 = Double.parseDouble(txtValor2.getText().replace(",", "."));

            Calculadora cal = new Calculadora();
            Double respuesta = cal.multiplicar(valor1, valor2);

            txtRespuesta.setText(respuesta + "");

            textArea1.append(valor1 + " × " + valor2 + " = " + respuesta + "\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos");
        }
    }

    /**
     * Valida que los campos no estén vacíos.
     *
     * @return true si los campos tienen valores
     */
    private boolean validarCampos() {
        if (txtValor1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1.");
            txtValor1.requestFocus();
            return false;
        } else if (txtValor2.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 2.");
            txtValor2.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Toma los números que el usuario puso en 'Valor 1' y 'Valor 2' y los suma.
     * Luego muestra el resultado en 'Respuesta' y también lo agrega al
     * historial que se ve en el área de texto. Si el usuario escribe algo que
     * no sea un número, muestra un mensaje de error.
     */
    private void sumarValores() {
        try {
            Double valor1 = Double.parseDouble(txtValor1.getText().replace(",", "."));
            Double valor2 = Double.parseDouble(txtValor2.getText().replace(",", "."));

            Calculadora cal = new Calculadora();
            Double respuesta = cal.sumar(valor1, valor2);

            txtRespuesta.setText(respuesta + "");

            textArea1.append(valor1 + " + " + valor2 + " = " + respuesta + "\n");

        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBorrarHistorial;
    private javax.swing.JButton btmCaF;
    private javax.swing.JButton btmDividir;
    private javax.swing.JButton btmFaC;
    private javax.swing.JButton btmMultiplicar;
    private javax.swing.JButton btmPotencia;
    private javax.swing.JButton btmRaiz;
    private javax.swing.JButton btmResetear;
    private javax.swing.JButton btmRestar;
    private javax.swing.JButton btmSumar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
