/*
 */
package vistas;

import gestionChoferes.*;
import gestionPago.*;
import gestionRutas.*;

/**
 *
 * @author ZoeyTato [Zoila Garcia 2021-1514]
 */
public class DialogVerPago extends javax.swing.JDialog {

    Chofer chofer;
    Ruta ruta;
    Pago pago;
    ChoferDAO controllerChofer = new ChoferDAO();
    RutaDAO controllerRuta = new RutaDAO();
    PagoDAO controllerPago = new PagoDAO();
    
    private Inicio home;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogVerPago.class.getName());

    /**
     * Creates new form DialogEditarChofer
     */
    public DialogVerPago(java.awt.Frame parent, boolean modal, int id, Inicio home) {
        super(parent, modal);
        this.home = home;
        initComponents();
        setLocationRelativeTo(parent);
        
        pago = controllerPago.leerPago(id);
        chofer = controllerChofer.cargarChofer(pago.getId());
        ruta = controllerRuta.cargarRuta(pago.getId());
        
        txtChofer.setText(chofer != null ? chofer.getNombre() + " " + chofer.getApellido() : "Sin chofer asignado");
        txtRuta.setText(ruta != null ? ruta.getNombre() : "Sin ruta asignada");
        txtMonto.setText("RD$" + String.valueOf(pago.getMonto()));
        txrMetodo.setText(pago.getMetodoPago());
        txtEstado.setText(pago.getEstadoPago());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtChofer = new javax.swing.JLabel();
        txtRuta = new javax.swing.JLabel();
        txtMonto = new javax.swing.JLabel();
        txrMetodo = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver pago");
        setBackground(new java.awt.Color(255, 254, 236));

        jPanel1.setBackground(new java.awt.Color(255, 254, 236));
        jPanel1.setForeground(new java.awt.Color(112, 112, 112));

        lblTitulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(23, 31, 38));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/007-coin32.png"))); // NOI18N
        lblTitulo.setText("Ver pago");
        lblTitulo.setIconTextGap(10);

        jSeparator1.setForeground(new java.awt.Color(112, 112, 112));

        btnAceptar.setBackground(new java.awt.Color(23, 31, 38));
        btnAceptar.setText("Cerrar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 31, 38));
        jLabel1.setText("Chofer:");

        lblAlerta.setForeground(new java.awt.Color(153, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(23, 31, 38));
        jLabel3.setText("Ruta:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(23, 31, 38));
        jLabel4.setText("Monto:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 31, 38));
        jLabel5.setText("Método:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(23, 31, 38));
        jLabel6.setText("Estado:");

        txtChofer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChofer.setForeground(new java.awt.Color(23, 31, 38));
        txtChofer.setText("Chofer:");

        txtRuta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRuta.setForeground(new java.awt.Color(23, 31, 38));
        txtRuta.setText("Ruta:");

        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(23, 31, 38));
        txtMonto.setText("Monto:");

        txrMetodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txrMetodo.setForeground(new java.awt.Color(23, 31, 38));
        txrMetodo.setText("Método:");

        txtEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(23, 31, 38));
        txtEstado.setText("Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblAlerta)
                        .addGap(88, 297, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txrMetodo)
                    .addComponent(txtMonto)
                    .addComponent(txtRuta)
                    .addComponent(txtChofer)
                    .addComponent(txtEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtChofer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRuta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txrMetodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAlerta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel txrMetodo;
    private javax.swing.JLabel txtChofer;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtMonto;
    private javax.swing.JLabel txtRuta;
    // End of variables declaration//GEN-END:variables
}
