/*
 */
package vistas;

import gestionChoferes.*;
import gestionPago.*;
import gestionRutas.*;
import gestionUsuarios.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ZoeyTato [Zoila Garcia 2021-1514]
 */
public class DialogEditarPago extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogEditarPago.class.getName());

    Pago pago;
    PagoDAO controller = new PagoDAO();
    private Inicio home;

    Usuario actual = Sesion.getInstancia().getUsuarioActual();
    int idUsuario = actual.getId(); // Para usarlo en filtros WHERE

    /**
     * Creates new form DialogEditarPago
     */
    public DialogEditarPago(java.awt.Frame parent, boolean modal, int id, Inicio home) {
        super(parent, modal);
        this.home = home;
        initComponents();
        cargarRutas();
        cargarChoferes();
        setLocationRelativeTo(parent);

        pago = controller.leerPago(id);

        txtMonto.setText(String.valueOf(pago.getMonto()));
        comboMetodo.setSelectedItem(pago.getMetodoPago());
        comboEstado.setSelectedItem(pago.getEstadoPago());
        seleccionarRuta(pago.getId_ruta());
        seleccionarChofer(pago.getId_chofer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRutas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblAlerta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboRuta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboChofer = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboMetodo = new javax.swing.JComboBox<>();
        comboEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear ruta");
        setBackground(new java.awt.Color(255, 254, 236));

        jPanel1.setBackground(new java.awt.Color(255, 254, 236));
        jPanel1.setForeground(new java.awt.Color(112, 112, 112));

        lblRutas.setBackground(new java.awt.Color(153, 153, 153));
        lblRutas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRutas.setForeground(new java.awt.Color(23, 31, 38));
        lblRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/007-coin32.png"))); // NOI18N
        lblRutas.setText("Editar pago");
        lblRutas.setIconTextGap(10);

        jSeparator1.setForeground(new java.awt.Color(112, 112, 112));

        btnCancelar.setBackground(new java.awt.Color(112, 112, 112));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnAceptar.setBackground(new java.awt.Color(23, 31, 38));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 31, 38));
        jLabel1.setText("Monto:");

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setForeground(new java.awt.Color(112, 112, 112));
        txtMonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMonto.setCaretColor(new java.awt.Color(112, 112, 112));
        txtMonto.addActionListener(this::txtMontoActionPerformed);

        lblAlerta.setForeground(new java.awt.Color(153, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(23, 31, 38));
        jLabel6.setText("Ruta:");

        comboRuta.setBackground(new java.awt.Color(255, 255, 255));
        comboRuta.setForeground(new java.awt.Color(112, 112, 112));
        comboRuta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboRuta.setMinimumSize(new java.awt.Dimension(64, 20));
        comboRuta.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(23, 31, 38));
        jLabel7.setText("Chofer:");

        comboChofer.setBackground(new java.awt.Color(255, 255, 255));
        comboChofer.setForeground(new java.awt.Color(112, 112, 112));
        comboChofer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboChofer.setMinimumSize(new java.awt.Dimension(64, 20));
        comboChofer.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(23, 31, 38));
        jLabel8.setText("Estado:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(23, 31, 38));
        jLabel9.setText("Método:");

        comboMetodo.setBackground(new java.awt.Color(255, 255, 255));
        comboMetodo.setForeground(new java.awt.Color(112, 112, 112));
        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transfer", "Tarjeta" }));
        comboMetodo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboMetodo.setMinimumSize(new java.awt.Dimension(64, 20));
        comboMetodo.setPreferredSize(new java.awt.Dimension(64, 20));
        comboMetodo.addActionListener(this::comboMetodoActionPerformed);

        comboEstado.setBackground(new java.awt.Color(255, 255, 255));
        comboEstado.setForeground(new java.awt.Color(112, 112, 112));
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Pagado" }));
        comboEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboEstado.setMinimumSize(new java.awt.Dimension(64, 20));
        comboEstado.setPreferredSize(new java.awt.Dimension(64, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRutas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMonto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAlerta)
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 112, Short.MAX_VALUE)
                                        .addComponent(btnAceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelar))
                                    .addComponent(comboChofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(comboEstado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboRuta, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlerta)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(comboChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Ruta rutaSeleccionada = (Ruta) comboRuta.getSelectedItem();
        if (rutaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una ruta.");
            return;
        }
        int idRuta = rutaSeleccionada.getId();
        
        Chofer choferSeleccionado = (Chofer) comboChofer.getSelectedItem();
        if (choferSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un chofer.");
            return;
        }
        int idChofer = choferSeleccionado.getId();
        
        if (txtMonto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe rellenar el monto.");
            return;
        }
                
        pago.setMonto(Double.parseDouble(txtMonto.getText()));
        pago.setEstadoPago(comboEstado.getSelectedItem().toString());
        pago.setMetodoPago(comboMetodo.getSelectedItem().toString());
        pago.setId_chofer(idChofer);
        pago.setId_ruta(idRuta);
        
        boolean resultado = controller.actualizarPago(pago);

        if (resultado) {
            System.out.println("Pago guardado");
        } else {
            System.out.println("Error al guardar");
            return;
        }
        
        dispose();
        home.mostrarPagos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMetodoActionPerformed
        
    }//GEN-LAST:event_comboMetodoActionPerformed

    private void cargarRutas() {
        RutaDAO rutaDAO = new RutaDAO();
        List<Ruta> rutas = rutaDAO.leerRutas(idUsuario); // filtra por usuario actual

        comboRuta.removeAllItems();

        for (Ruta ruta : rutas) {
            comboRuta.addItem(ruta);
        }
    }

    private void cargarChoferes() {
        ChoferDAO choferDAO = new ChoferDAO();
        List<Chofer> choferes = choferDAO.listar(idUsuario); // filtra por usuario actual

        comboChofer.removeAllItems();

        for (Chofer chofer : choferes) {
            comboChofer.addItem(chofer);
        }
    }

    private void seleccionarRuta(int idRuta) {
        for (int i = 0; i < comboRuta.getItemCount(); i++) {
            Ruta ruta = comboRuta.getItemAt(i);
            if (ruta.getId() == idRuta) {
                comboRuta.setSelectedIndex(i);
                break;
            }
        }
    }

    private void seleccionarChofer(int idChofer) {
        for (int i = 0; i < comboChofer.getItemCount(); i++) {
            Chofer chofer = comboChofer.getItemAt(i);
            if (chofer.getId() == idChofer) {
                comboChofer.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Chofer> comboChofer;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JComboBox<Ruta> comboRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblRutas;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
