/*
 */
package vistas;

import gestionChoferes.*;
import gestionRutas.*;
import gestionUsuarios.*;
import gestionVehiculos.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ZoeyTato [Zoila Garcia 2021-1514]
 */
public class DialogCrearVehiculo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogCrearVehiculo.class.getName());
    private Inicio home;

    Usuario actual = Sesion.getInstancia().getUsuarioActual();
    int idUsuario = actual.getId(); // Para usarlo en filtros WHERE

    /**
     * Creates new form DialogCrearVehiculo
     */
    public DialogCrearVehiculo(java.awt.Frame parent, boolean modal, Inicio home) {
        super(parent, modal);
        this.home = home;
        initComponents();
        cargarRutas();
        cargarChoferes();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRutas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblAlerta = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboRuta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboChofer = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear vehículo");
        setBackground(new java.awt.Color(255, 254, 236));

        jPanel1.setBackground(new java.awt.Color(255, 254, 236));
        jPanel1.setForeground(new java.awt.Color(112, 112, 112));

        lblRutas.setBackground(new java.awt.Color(153, 153, 153));
        lblRutas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRutas.setForeground(new java.awt.Color(23, 31, 38));
        lblRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/008-car32.png"))); // NOI18N
        lblRutas.setText("Crear vehículo");
        lblRutas.setIconTextGap(10);

        jSeparator1.setForeground(new java.awt.Color(112, 112, 112));

        btnCancelar.setBackground(new java.awt.Color(112, 112, 112));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnAceptar.setBackground(new java.awt.Color(23, 31, 38));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 31, 38));
        jLabel1.setText("Marca:");

        txtMarca.setBackground(new java.awt.Color(255, 255, 255));
        txtMarca.setForeground(new java.awt.Color(112, 112, 112));
        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMarca.setCaretColor(new java.awt.Color(112, 112, 112));
        txtMarca.addActionListener(this::txtMarcaActionPerformed);

        lblAlerta.setForeground(new java.awt.Color(153, 0, 0));

        txtModelo.setBackground(new java.awt.Color(255, 255, 255));
        txtModelo.setForeground(new java.awt.Color(112, 112, 112));
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtModelo.setCaretColor(new java.awt.Color(112, 112, 112));
        txtModelo.addActionListener(this::txtModeloActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(23, 31, 38));
        jLabel3.setText("Modelo:");

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setForeground(new java.awt.Color(112, 112, 112));
        txtMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMatricula.setCaretColor(new java.awt.Color(112, 112, 112));
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(23, 31, 38));
        jLabel4.setText("Matrícula:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(23, 31, 38));
        jLabel6.setText("Ruta:");

        comboRuta.setBackground(new java.awt.Color(255, 255, 255));
        comboRuta.setForeground(new java.awt.Color(112, 112, 112));
        comboRuta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboRuta.setMinimumSize(new java.awt.Dimension(64, 20));
        comboRuta.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(23, 31, 38));
        jLabel7.setText("Chofer:");

        comboChofer.setBackground(new java.awt.Color(255, 255, 255));
        comboChofer.setForeground(new java.awt.Color(112, 112, 112));
        comboChofer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboChofer.setMinimumSize(new java.awt.Dimension(64, 20));
        comboChofer.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(23, 31, 38));
        jLabel8.setText("Año:");

        txtAno.setBackground(new java.awt.Color(255, 255, 255));
        txtAno.setForeground(new java.awt.Color(112, 112, 112));
        txtAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtAno.setCaretColor(new java.awt.Color(112, 112, 112));
        txtAno.addActionListener(this::txtAnoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca)
                            .addComponent(txtMatricula)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAlerta)
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 112, Short.MAX_VALUE)
                                        .addComponent(btnAceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelar))
                                    .addComponent(comboRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAno))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRutas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addComponent(comboChofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlerta)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(comboRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        Vehiculo vehiculo = new Vehiculo();
        VehiculoDAO controller = new VehiculoDAO();
        
        Ruta rutaSeleccionada = (Ruta) comboRuta.getSelectedItem();
        if (rutaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una ruta.");
            return;
        }
        int idRuta = rutaSeleccionada.getId();
        
        Chofer choferSeleccionado = (Chofer) comboChofer.getSelectedItem();
        if (choferSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un chofer.");
            return;
        }
        int idChofer = choferSeleccionado.getId();
        
        String modelo = txtModelo.getText();
        String marca = txtMarca.getText();
        String ano = txtAno.getText();
        String matricula = txtMatricula.getText();
        
        if (modelo.isEmpty() || marca.isEmpty() || ano.isEmpty() || matricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos.");
            return;
        }
        
        vehiculo.setMarca(marca);
        vehiculo.setModelo(modelo);
        vehiculo.setAño(ano);
        vehiculo.setMatricula(matricula);
        vehiculo.setIdChofer(idChofer);
        vehiculo.setIdRuta(idRuta);
        vehiculo.setIdUsuario(idUsuario);
        
        int resultado = controller.agregar(vehiculo);
        
        if (resultado == 1) {
            System.out.println("Vehiculo guardado");
        } else {
            System.out.println("Error al guardar");
            return;
        }
        
        dispose();
        home.mostrarVehiculos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void cargarRutas() {
        RutaDAO rutaDAO = new RutaDAO();
        List<Ruta> rutas = rutaDAO.leerRutas(idUsuario); // filtra por usuario actual

        comboRuta.removeAllItems();

        for (Ruta ruta : rutas) {
            comboRuta.addItem(ruta);
        }
    }

    private void cargarChoferes() {
        ChoferDAO choferDAO = new ChoferDAO();
        List<Chofer> choferes = choferDAO.listar(idUsuario); // filtra por usuario actual

        comboChofer.removeAllItems();

        for (Chofer chofer : choferes) {
            comboChofer.addItem(chofer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Chofer> comboChofer;
    private javax.swing.JComboBox<Ruta> comboRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblRutas;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
