package registroacademico;

public class RegistroAcademicoGUI extends javax.swing.JPanel {
    Estudiante estudiante = new Estudiante();
    int suma;
    /**
     * Creates new form RegistroAcademicoGUI
     */
    public RegistroAcademicoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        txtMatricula = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JLabel();
        dtoCarrera = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtPractica = new javax.swing.JLabel();
        txtParciales = new javax.swing.JLabel();
        txtAsignaciones = new javax.swing.JLabel();
        txtExamenFinal = new javax.swing.JLabel();
        btnCacularResultado = new javax.swing.JButton();
        txtNotaTotal = new javax.swing.JLabel();
        dtoNotaTotal = new javax.swing.JTextField();
        dtoPracticas = new javax.swing.JTextField();
        dtoParciales = new javax.swing.JTextField();
        dtoAsignaciones = new javax.swing.JTextField();
        dtoExamenFinal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        dtoNombre = new javax.swing.JTextField();
        dtoMatricula = new javax.swing.JTextField();

        txtMatricula.setBackground(new java.awt.Color(0, 0, 0));
        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtMatricula.setText("Matrícula");

        txtCarrera.setBackground(new java.awt.Color(0, 0, 0));
        txtCarrera.setForeground(new java.awt.Color(0, 0, 0));
        txtCarrera.setText("Carrera");

        dtoCarrera.setBackground(new java.awt.Color(204, 204, 204));
        dtoCarrera.setForeground(new java.awt.Color(0, 0, 0));
        dtoCarrera.setToolTipText("Escriba su carrera");
        dtoCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoCarreraActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        txtPractica.setBackground(new java.awt.Color(0, 0, 0));
        txtPractica.setForeground(new java.awt.Color(0, 0, 0));
        txtPractica.setText("Prácticas");

        txtParciales.setBackground(new java.awt.Color(0, 0, 0));
        txtParciales.setForeground(new java.awt.Color(0, 0, 0));
        txtParciales.setText("Parciales");

        txtAsignaciones.setBackground(new java.awt.Color(0, 0, 0));
        txtAsignaciones.setForeground(new java.awt.Color(0, 0, 0));
        txtAsignaciones.setText("Asignaciones");

        txtExamenFinal.setBackground(new java.awt.Color(0, 0, 0));
        txtExamenFinal.setForeground(new java.awt.Color(0, 0, 0));
        txtExamenFinal.setText("Examen Final");

        btnCacularResultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCacularResultado.setText("Calcular Resultado");
        btnCacularResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCacularResultado.setMaximumSize(new java.awt.Dimension(163, 27));
        btnCacularResultado.setMinimumSize(new java.awt.Dimension(163, 27));
        btnCacularResultado.setPreferredSize(new java.awt.Dimension(163, 27));
        btnCacularResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacularResultadoActionPerformed(evt);
            }
        });

        txtNotaTotal.setBackground(new java.awt.Color(0, 0, 0));
        txtNotaTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtNotaTotal.setText("Nota total");

        dtoNotaTotal.setBackground(new java.awt.Color(255, 255, 255));
        dtoNotaTotal.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        dtoNotaTotal.setForeground(new java.awt.Color(0, 0, 0));
        dtoNotaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dtoNotaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoNotaTotalActionPerformed(evt);
            }
        });

        dtoPracticas.setBackground(new java.awt.Color(255, 255, 255));
        dtoPracticas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dtoPracticas.setForeground(new java.awt.Color(0, 0, 0));
        dtoPracticas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dtoPracticas.setToolTipText("Escriba la puntución total de prácticas");
        dtoPracticas.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dtoPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoPracticasActionPerformed(evt);
            }
        });

        dtoParciales.setBackground(new java.awt.Color(255, 255, 255));
        dtoParciales.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dtoParciales.setForeground(new java.awt.Color(0, 0, 0));
        dtoParciales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dtoParciales.setToolTipText("Escriba la puntución total de parciales");
        dtoParciales.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dtoParciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoParcialesActionPerformed(evt);
            }
        });

        dtoAsignaciones.setBackground(new java.awt.Color(255, 255, 255));
        dtoAsignaciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dtoAsignaciones.setForeground(new java.awt.Color(0, 0, 0));
        dtoAsignaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dtoAsignaciones.setToolTipText("Escriba la puntución total de asignaciones");
        dtoAsignaciones.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dtoAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoAsignacionesActionPerformed(evt);
            }
        });

        dtoExamenFinal.setBackground(new java.awt.Color(255, 255, 255));
        dtoExamenFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dtoExamenFinal.setForeground(new java.awt.Color(0, 0, 0));
        dtoExamenFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dtoExamenFinal.setToolTipText("Escriba la puntución del examen final");
        dtoExamenFinal.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dtoExamenFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoExamenFinalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPractica, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dtoPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtoParciales, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsignaciones)
                            .addComponent(dtoAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExamenFinal)
                            .addComponent(dtoExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnCacularResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNotaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtoNotaTotal))
                        .addGap(155, 155, 155))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPractica)
                    .addComponent(txtParciales)
                    .addComponent(txtAsignaciones)
                    .addComponent(txtExamenFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtoPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtoParciales, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtoAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtoExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(txtNotaTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtoNotaTotal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCacularResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Registro Académico");

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre completo");

        dtoNombre.setBackground(new java.awt.Color(204, 204, 204));
        dtoNombre.setForeground(new java.awt.Color(0, 0, 0));
        dtoNombre.setToolTipText("Escriba su nombre");
        dtoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoNombreActionPerformed(evt);
            }
        });

        dtoMatricula.setBackground(new java.awt.Color(204, 204, 204));
        dtoMatricula.setForeground(new java.awt.Color(0, 0, 0));
        dtoMatricula.setToolTipText("Escriba su matrícula");
        dtoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dtoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addGap(128, 128, 128)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtMatricula)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dtoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtCarrera)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre)
                    .addComponent(txtMatricula)
                    .addComponent(txtCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Recibe cadena de texto y valida que no esté apto para ser una carrera
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoCarreraActionPerformed
        String carrera = dtoCarrera.getText();
        
        if(carrera.trim().isEmpty()){
            jOptionPane1.showMessageDialog(this, "Debe ingresar una carrera");
            return;
        } 
        else if(!carrera.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")){
            jOptionPane1.showMessageDialog(this, "La carrera solo debe contener letras");
            return;
        }
        
        estudiante.setCarrera(carrera);
    }//GEN-LAST:event_dtoCarreraActionPerformed

    /**
     * Boton que calcula la nota total y valida que esté haya aprobado o reprobado
     * @param evt evento que ocurre al presionar enter
     */
    private void btnCacularResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacularResultadoActionPerformed
        int practicas = estudiante.getPracticas();
        int parciales = estudiante.getParciales();
        int asignaciones = estudiante.getAsignaciones();
        int examenFinal = estudiante.getExamenFinal();
        
        suma = practicas + parciales + asignaciones + examenFinal;
        dtoNotaTotal.setText(String.valueOf(suma));
        
        if(suma >= 60){
            jLabel9.setText("Aprobado");
            return;
        }
        jLabel9.setText("Reprobado");
    }//GEN-LAST:event_btnCacularResultadoActionPerformed

    /**
     * Recibe cadena de texto y valida que esté apto para ser un nombre
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoNombreActionPerformed
        String nombre = dtoNombre.getText();
        
        if(nombre.trim().isEmpty()){
            jOptionPane1.showMessageDialog(this, "Debe ingresar un nombre");
            return;
        } 
        else if(!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")){
            jOptionPane1.showMessageDialog(this, "El nombre solo debe contener letras");
            return;
        }
        
        estudiante.setNombre(nombre);
    }//GEN-LAST:event_dtoNombreActionPerformed

    /**
     * Recibe cadena de texto y valida que esté apto para ser una matrícula
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoMatriculaActionPerformed
        String matricula = dtoMatricula.getText();
        
        if(matricula.trim().isEmpty()){
            jOptionPane1.showMessageDialog(this, "Debe ingresar una matrícula");
            return;
        } 
        
        estudiante.setMatricula(matricula);
    }//GEN-LAST:event_dtoMatriculaActionPerformed

    private void dtoNotaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoNotaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtoNotaTotalActionPerformed

    /**
     * Recibe cadena de texto, lo convierte a entero y valida que esté apto para ser la puntuación total de prácticas dentro de un rango
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoPracticasActionPerformed
        try{
            int practicas = Integer.parseInt(dtoPracticas.getText());

            if (practicas < 0 || practicas > 40) {
                jOptionPane1.showMessageDialog(this, "La nota debe estar entre 0 y 40");
                return;
            }
            estudiante.setPracticas(practicas);
        }
        catch (NumberFormatException e){
            jOptionPane1.showMessageDialog(this, "No inserto un valor en el campo o el valor ingresado no es un número entero");
        }        
    }//GEN-LAST:event_dtoPracticasActionPerformed

    /**
     * Recibe cadena de texto, lo convierte a entero y valida que esté apto para ser la puntuación total  de parciales dentro de un rango
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoParcialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoParcialesActionPerformed
        try{
            int parciales = Integer.parseInt(dtoParciales.getText());

            if (parciales < 0 || parciales > 20) {
                jOptionPane1.showMessageDialog(this, "La nota debe estar entre 0 y 20");
                return;
            }
            estudiante.setParciales(parciales);
        }
        catch (NumberFormatException e){
            jOptionPane1.showMessageDialog(this, "No inserto un valor en el campo o el valor ingresado no es un número entero");
        } 
    }//GEN-LAST:event_dtoParcialesActionPerformed

    /**
     * Recibe cadena de texto, lo convierte a entero y valida que esté apto para ser la puntuación total de asignaciones dentro de un rango
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoAsignacionesActionPerformed
        try{
            int asignaciones = Integer.parseInt(dtoAsignaciones.getText());

            if (asignaciones < 0 || asignaciones > 20) {
                jOptionPane1.showMessageDialog(this, "La nota debe estar entre 0 y 20");
                return;
            }
            estudiante.setAsignaciones(asignaciones);
        }
        catch (NumberFormatException e){
            jOptionPane1.showMessageDialog(this, "No inserto un valor en el campo o el valor ingresado no es un número entero");
        } 
    }//GEN-LAST:event_dtoAsignacionesActionPerformed

    /**
     * Recibe cadena de texto, lo convierte a entero y valida que esté apto para ser la puntuación del examen final dentro de un rango
     * @param evt evento que ocurre al presionar enter
     */
    private void dtoExamenFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtoExamenFinalActionPerformed
        try{
            int examenFinal = Integer.parseInt(dtoExamenFinal.getText());

            if (examenFinal < 0 || examenFinal > 20) {
                jOptionPane1.showMessageDialog(this, "La nota debe estar entre 0 y 20");
                return;
            }
            estudiante.setExamenFinal(examenFinal);
        }
        catch (NumberFormatException e){
            jOptionPane1.showMessageDialog(this, "No inserto un valor en el campo o el valor ingresado no es un número entero");
        } 
    }//GEN-LAST:event_dtoExamenFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCacularResultado;
    private javax.swing.JTextField dtoAsignaciones;
    private javax.swing.JTextField dtoCarrera;
    private javax.swing.JTextField dtoExamenFinal;
    private javax.swing.JTextField dtoMatricula;
    private javax.swing.JTextField dtoNombre;
    private javax.swing.JTextField dtoNotaTotal;
    private javax.swing.JTextField dtoParciales;
    private javax.swing.JTextField dtoPracticas;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAsignaciones;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JLabel txtExamenFinal;
    private javax.swing.JLabel txtMatricula;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNotaTotal;
    private javax.swing.JLabel txtParciales;
    private javax.swing.JLabel txtPractica;
    // End of variables declaration//GEN-END:variables
}
